#ifndef TAINTEDPARSON_WASM_H_GENERATED_
#define TAINTEDPARSON_WASM_H_GENERATED_

#define WASM_CURR_MODULE_PREFIX 
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

#define WASM_CURR_ADD_PREFIX(x) WASM_RT_PASTE(WASM_CURR_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#ifndef WASM_DONT_EXPORT_FUNCS
# if defined(_WIN32)
#   define FUNC_EXPORT __declspec(dllexport)
# else
#   define FUNC_EXPORT
# endif
#else
# define FUNC_EXPORT
#endif

FUNC_EXPORT wasm2c_sandbox_funcs_t WASM_CURR_ADD_PREFIX(get_wasm2c_sandbox_info)();

struct wasm2c_sandbox_t;
typedef struct wasm2c_sandbox_t wasm2c_sandbox_t;

/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void*, u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void*, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_getZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_prestat_dir_name' */
extern u32 Z_wasi_snapshot_preview1Z_fd_prestat_dir_nameZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'proc_exit' */
extern void Z_wasi_snapshot_preview1Z_proc_exitZ_vi(void*, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_getZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_open' */
extern u32 Z_wasi_snapshot_preview1Z_path_openZ_iiiiiijjii(void*, u32, u32, u32, u32, u32, u64, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_readlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_readlinkZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_filestat_set_times' */
extern u32 Z_wasi_snapshot_preview1Z_path_filestat_set_timesZ_iiiiijji(void*, u32, u32, u32, u32, u64, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_unlink_file' */
extern u32 Z_wasi_snapshot_preview1Z_path_unlink_fileZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_remove_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_remove_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_create_directory' */
extern u32 Z_wasi_snapshot_preview1Z_path_create_directoryZ_iiii(void*, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_readdir' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readdirZ_iiiiji(void*, u32, u32, u32, u64, u32);
/* import: 'wasi_snapshot_preview1' 'path_symlink' */
extern u32 Z_wasi_snapshot_preview1Z_path_symlinkZ_iiiiii(void*, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_link' */
extern u32 Z_wasi_snapshot_preview1Z_path_linkZ_iiiiiiii(void*, u32, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'path_rename' */
extern u32 Z_wasi_snapshot_preview1Z_path_renameZ_iiiiiii(void*, u32, u32, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_fdstat_set_flags' */
extern u32 Z_wasi_snapshot_preview1Z_fd_fdstat_set_flagsZ_iii(void*, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_read' */
extern u32 Z_wasi_snapshot_preview1Z_fd_readZ_iiiii(void*, u32, u32, u32, u32);

FUNC_EXPORT u32 w2c_json_parse_file_with_comments(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_read_file(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_parse_string_with_comments(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_parson_string_tainted_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_tainted_parson_strdup(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_remove_comments(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_tainted_parson_strndup(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_getn_value(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_dotget_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_value_get_object(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_type(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f64 w2c_json_object_dotget_number(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f64 w2c_json_value_get_number(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_dotget_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_value_get_array(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_get_name(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_value_at(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_wrapping_value(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_array_get_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_array_get_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_type_tainted(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_object_tainted(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_string(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_boolean(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_value_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_object_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_array_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_object(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_object_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_array(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_array_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_number(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT u32 w2c_json_value_init_boolean(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_null(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_serialize_to_buffer_pretty(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_serialization_size_pretty(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_serialize_to_buffer_r(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_append_string(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_append_indent(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_serialize_string(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_serialize_to_file_pretty(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_serialize_to_string_pretty(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_free_serialized_string(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_array_remove(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_clear(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_dlmalloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dlfree(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_calloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_realloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_dispose_chunk(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_posix_memalign(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_internal_memalign(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_aligned_alloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_malloc_usable_size(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_abort(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_sbrk(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_ftell(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_ferror(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fwrite(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fputs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fread(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_fseek(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_rewind(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_vsnprintf(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sn_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_vsprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_sprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fflush(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dummy(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fclose(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strerror(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_writev(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_vfprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf_core(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c_pop_arg(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_close(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_fstatat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_getcwd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c__Exit(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_internal_register_preopened_fd(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_chdir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_openat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_faccessat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_readlinkat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_utimensat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_mkdirat(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fdopendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_opendirat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_scandirat(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sel_true(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_symlinkat(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_linkat(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_renameat(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_open(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_access(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_readlink(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_stat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_lstat(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_utime(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_unlink(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_rmdir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_remove(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_mkdir(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_opendir(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_scandir(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_symlink(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_link(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_rename(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_fcntl(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_readv(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_read(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fopen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strdup(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_memmove(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strstr(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strcmp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strnlen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memcpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strncmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strcpy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memset(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strlen(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strchr(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memchr(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strncpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_memcmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_dummy_1(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_qsort(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT void w2c_trinkle(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_wctomb(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_wcrtomb(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f64 w2c_frexp(wasm2c_sandbox_t* const, f64, u32);

#ifdef __cplusplus
}
#endif

#endif  /* TAINTEDPARSON_WASM_H_GENERATED_ */
