#ifndef TAINTED_WASM_H_GENERATED_
#define TAINTED_WASM_H_GENERATED_

#define WASM_CURR_MODULE_PREFIX 
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

#define WASM_CURR_ADD_PREFIX(x) WASM_RT_PASTE(WASM_CURR_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#ifndef WASM_DONT_EXPORT_FUNCS
# if defined(_WIN32)
#   define FUNC_EXPORT __declspec(dllexport)
# else
#   define FUNC_EXPORT
# endif
#else
# define FUNC_EXPORT
#endif

FUNC_EXPORT wasm2c_sandbox_funcs_t WASM_CURR_ADD_PREFIX(get_wasm2c_sandbox_info)();

struct wasm2c_sandbox_t;
typedef struct wasm2c_sandbox_t wasm2c_sandbox_t;

/* import: 'wasi_snapshot_preview1' 'fd_write' */
extern u32 Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void*, u32, u32, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_seek' */
extern u32 Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void*, u32, u64, u32, u32);
/* import: 'wasi_snapshot_preview1' 'fd_close' */
extern u32 Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void*, u32);

FUNC_EXPORT u32 w2c_parson_string_tainted_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_tainted_parson_strndup(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_tainted_parson_strdup(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_verify_utf8_sequence(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_num_bytes_in_utf8_sequence(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_is_decimal(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_addn(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_object_getn_value(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_object_resize(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_wrapping_value(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_get_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_remove_internal(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_json_value_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_type(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_object_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_array_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_object_dotremove_internal(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_value_get_object(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_array_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_string_no_copy(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_parse_utf16(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_parse_utf16_hex(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_hex_char_to_int(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_get_quoted_string(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_skip_quotes(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_parse_string_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_parse_boolean_value(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_boolean(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_parse_number_value(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_number(wasm2c_sandbox_t* const, f64);
FUNC_EXPORT u32 w2c_json_serialize_to_buffer_r(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_value_get_array(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_array_get_count(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_append_string(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_append_indent(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_array_get_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_name(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_serialize_string(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_value_get_string(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_get_boolean(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT f64 w2c_json_value_get_number(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_parse_string_with_comments(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_remove_comments(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_object_dotget_value(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f64 w2c_json_object_dotget_number(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_dotget_array(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_get_value_at(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_init(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_value_init_object(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_value_init_array(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_value_init_null(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_json_serialize_to_buffer_pretty(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_json_serialization_size_pretty(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_serialize_to_string_pretty(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_json_free_serialized_string(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_json_array_remove(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_json_object_clear(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_malloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_dlmalloc(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_free(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_dlfree(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_calloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_realloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_dispose_chunk(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_posix_memalign(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_internal_memalign(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_aligned_alloc(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_malloc_usable_size(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT void w2c_abort(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_sbrk(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_vsnprintf(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_sn_write(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_vsprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_sprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fwrite(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_strerror(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_writev(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_fputs(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_vfprintf(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_printf_core(wasm2c_sandbox_t* const, u32, u32, u32, u32, u32);
FUNC_EXPORT void w2c_pop_arg(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported(wasm2c_sandbox_t* const);
FUNC_EXPORT u32 w2c_close(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_memmove(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strstr(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strcmp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_strnlen(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memcpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strncmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strcpy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memset(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strlen(wasm2c_sandbox_t* const, u32);
FUNC_EXPORT u32 w2c_strchr(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_memchr(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_strncpy(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_memcmp(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT u32 w2c_dummy(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u64 w2c_scanexp(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f32 w2c_strtof(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT f64 w2c_strtod(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT void w2c_strtold(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_long_double_not_supported_1(wasm2c_sandbox_t* const);
FUNC_EXPORT f32 w2c_strtof_l(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f64 w2c_strtod_l(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT void w2c_strtold_l(wasm2c_sandbox_t* const, u32, u32, u32, u32);
FUNC_EXPORT u32 w2c_wctomb(wasm2c_sandbox_t* const, u32, u32);
FUNC_EXPORT u32 w2c_wcrtomb(wasm2c_sandbox_t* const, u32, u32, u32);
FUNC_EXPORT f64 w2c_frexp(wasm2c_sandbox_t* const, f64, u32);
FUNC_EXPORT f64 w2c_scalbn(wasm2c_sandbox_t* const, f64, u32);
FUNC_EXPORT f64 w2c_fmod(wasm2c_sandbox_t* const, f64, f64);

#ifdef __cplusplus
}
#endif

#endif  /* TAINTED_WASM_H_GENERATED_ */
